site_name: AFSVHH Lehrgänge
site_url: https://clinic.afsvhh.de
edit_uri: edit/main/docs/
theme:
    name: material
    logo: assets/images/afsvhh.png
    favicon: assets/images/favicon.png
    locale: de
    palette:
        primary: black
    features:
        - navigation.tabs
nav:
    - 'index.md'
    - 'B.md'
    - 'C.md'
    - 'D.md'
    - 'E.md'
    - '| Downloads': 'https://afsvd.de/downloads/'

plugins:
    - search:
          lang: de
    - git-revision-date-localized:
          enable_creation_date: false
          fallback_to_build_date: false
          type: iso_datetime
markdown_extensions:
    - toc:
          permalink: '#'
    - admonition
    - tables
    - attr_list
    - def_list
    - md_in_html
    - meta
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
